[colors]
foreground = "{foreground}"
background = "{background}"

cursor_bg = "{cursor}"
cursor_fg = "{background}"
cursor_border = "{color2}"

selection_fg = "{background}"
selection_bg = "{foreground}"

scrollbar_thumb = "{color8}"
split = "{color8}"

ansi = [
    "{color0}",
    "{color1}",
    "{color2}",
    "{color3}",
    "{color4}",
    "{color5}",
    "{color6}",
    "{color7}",
]

brights = [
    "{color8}",
    "{color9}",
    "{color10}",
    "{color11}",
    "{color12}",
    "{color13}",
    "{color14}",
    "{color15}",
]

[colors.tab_bar]
background = "{background}"

[colors.tab_bar.active_tab]
fg_color = "{background}"
bg_color = "{foreground}"

[colors.tab_bar.inactive_tab]
fg_color = "{foreground}"
bg_color = "{background}"

