IgnorePath '/etc/hosts'
IgnorePath '/etc/fstab'
IgnorePath '/etc/group'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/passwd'
IgnorePath '/etc/shadow'
IgnorePath '/etc/xml/catalog'
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/shells'
IgnorePath '/etc/dconf/db/*'
IgnorePath '/etc/issue'
IgnorePath '/etc/lsb-release'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/NetworkManager/system-connections/*'
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/etc/cups/subscriptions.conf*'
IgnorePath '/etc/printcap'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/skel/.bashrc'
IgnorePath '/etc/*-'
IgnorePath '/etc/cni/net.d'
IgnorePath '/etc/hostname'

IgnorePath '/etc/.updated'
IgnorePath '/var/.updated'

IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/os-release'
IgnorePath '/usr/lib/jvm/*'
IgnorePath '/usr/lib/node_modules/*'
IgnorePath '/usr/lib/vlc/plugins/plugins.dat'
IgnorePath '/usr/lib/graphviz/config6'

IgnorePath '/.snap*'
IgnorePath '/lost+found'
IgnorePath '/etc/arch-release'

IgnorePath '/nix/*'
IgnorePath '/opt/*'

IgnorePath '*mullvad*'
