/
/bin
/boot
/dev
/etc
/home
/lib
/proc
/root
/sbin
/sys
/usr
/usr/bin
/usr/include
/usr/lib
/usr/local
/usr/local/bin
/usr/local/include
/usr/local/sbin
/usr/local/share
/usr/sbin
/usr/share
/usr/src
/var
/home
/home/alex
/home/alex/src
/home/alex/work
/home/alex/work/mkosi-poc
/home/alex/files
/home/alex/cfg
/home/alex/cfg/user
/home/alex/cfg/user/files
/home/alex/cfg/system
/home/alex/.config
/home/alex/.cache
